### PR TITLE
Handle escaped double quotes

### PR DESCRIPTION
**Pull request by fangyi-zhou**

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
By the way, I think the updated build system seem to cause issues for development. It was a little difficult for me to get the correct dependencies. I had to revert the top 2 commits in order to build on my mac.

**Comment by auduchinok** [comment]
> By the way, I think the updated build system seem to cause issues for development. It was a little difficult for me to get the correct dependencies. I had to revert the top 2 commits in order to build on my mac.

Sorry for that. It was an attempt to migrate the build process of some of the dependencies at [QuickGraph repo](https://github.com/YaccConstructor/QuickGraph) which this project was initially implemented for. Unfortunately, the author of these commits didn't finish it all so you've encountered a somewhat broken state. I'll appreciate if you open a PR reverting these commits or updating it to newer tools.

**Review by auduchinok — APPROVED** [review]

**Comment by auduchinok** [comment]
@fangyi-zhou Thank you for this.

**Comment by fangyi-zhou** [comment]
Reverting top 2 commits only partially solves the issue, there were still some missing bits and pieces. e.g. FsYard had missing FSharp.Core which I had to manually copy to `lib`. There were issues with `ILMerge` as well but I didn't invest time to take care of that.

Also, it is possible to make a new release on NuGet? I would be very grateful if you could do so.

**Pull request merged**
